
import nurse1 from '../../assets/nurse1.jpg'
import nurse2 from '../../assets/nurse2.jpg'
import nurse3 from '../../assets/nurse3.jpg'
import nurse4 from '../../assets/nurse4.jpg'

export default [
    {
        id: 1,
        image: nurse1,
        name: 'gfgfg',
        email: '',
        phone: '',
        education: '',
        skills: 'Child care',
    },
    {
        id: 2,
        image: nurse1,
        name: 'dfsfg',
        email: '',
        phone: '',
        education: '',
        skills: 'Child care',
    },
    {
        id: 3,
        image: nurse1,
        name: 'sdfs',
        email: '',
        phone: '',
        education: '',
        skills: 'Old Care',
    },
    {
        id: 4,
        image: nurse1,
        name: '',
        email: '',
        phone: '',
        education: '',
        skills: 'Injections',
    },
    {
        id: 5,
        image: nurse1,
        name: '',
        email: '',
        phone: '',
        education: '',
        skills: 'Old Care',
    },
    {
        id: 6,
        image: nurse2,
        name: '',
        email: '',
        phone: '',
        education: '',
        skills: 'Injections',
    },
    {
        id: 7,
        image: nurse2,
        name: '',
        email: '',
        phone: '',
        education: '',
        skills: 'Old Care',
    },
    {
        id: 8,
        image: nurse2,
        name: '',
        email: '',
        phone: '',
        education: '',
        skills: 'Child care',
    },
    {
        id: 9,
        image: nurse2,
        name: '',
        email: '',
        phone: '',
        education: '',
        skills: 'Child care',
    },
    {
        id: 10,
        image: nurse2,
        name: '',
        email: '',
        phone: '',
        education: '',
        skills: 'Child care',
    },
    {
        id: 11,
        image: nurse3,
        name: '',
        email: '',
        phone: '',
        education: '',
        skills: 'Child care',
    },
    {
        id: 12,
        image: nurse3,
        name: '',
        email: '',
        phone: '',
        education: '',
        skills: 'Injections',
    },
    {
        id: 13,
        image: nurse3,
        name: '',
        email: '',
        phone: '',
        education: '',
        skills: 'Old Care',
    },
    {
        id: 14,
        image: nurse3,
        name: '',
        email: '',
        phone: '',
        education: '',
        skills: 'Injections',
    },
    {
        id: 15,
        image: nurse3,
        name: '',
        email: '',
        phone: '',
        education: '',
        skills: 'Old Care',
    },
    {
        id: 16,
        image: nurse4,
        name: '16',
        email: '',
        phone: '',
        education: '',
        skills: 'Old Care',
    },
    {
        id: 17,
        image: nurse4,
        name: '17',
        email: '',
        phone: '',
        education: '',
        skills: 'Injections',
    },
    {
        id: 18,
        image: nurse4,
        name: '18',
        email: '',
        phone: '',
        education: '',
        skills: 'Injections',
    },

    {
        id: 20,
        image: nurse4,
        name: '20',
        email: '',
        phone: '',
        education: '',
        skills: 'Old Care',
    },
    {
        id: 21,
        image: nurse4,
        name: '21',
        email: '',
        phone: '',
        education: '',
        skills: 'Old Care',
    },
];